### ISSUE TITLE
Remove site-map.php template

### ISSUE THREAD

**Issue by TimBHowe** [hallme/scaffolding#105]
as the template relies on the installation of a plugin it should be removed. We should move this into a gist or it's own separate repository if we intend to keep using it. 

Also with the release of WordPress SEO 2.3, Release Date: July 21st, 2015, they have removed the sitemap exclude feature to be set within the WordPress SEO admin rather then per page settings. This template should be reviewed and updated.

**Comment by jlavoie13** [comment]
We have other references to yoast in the theme and also wpengine.

**Comment by jlavoie13** [comment]
Keeping, reviewed here 1515374
