### ISSUE TITLE
Scaffolding Caption not showing correctly

### ISSUE THREAD

**Issue by bryanf123** [hallme/scaffolding#119]
When I add a caption to an image it shows up correctly in the Wordpress editor but not on the front end of the site. On the front end it shows the code around the image. How do I correct this.

I have tried deactivating all plugins and that did not work.
I reverted to another theme and doing that fixed it which leads me to think its an issue in the theme.

any help would be greatly appreciated.

**Comment by jlavoie13** [comment]
Hi, try commenting out these lines in base-functions.php and see if that works for you

`add_shortcode( 'wp_caption', 'scaffolding_fix_img_caption_shortcode' );
add_shortcode( 'caption', 'scaffolding_fix_img_caption_shortcode' );`

**Comment by bryanf123** [comment]
Jlavoie13 this worked perfectly thank you!
