### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by bryanf123** [hallme/scaffolding#122]
I have been trying to us an image gallery plugin because I need the next arrows to scroll through the images but now the stock lightbox opens along with the lightbox from the plugin how can I disable the stock lightbox?

**Comment by jlavoie13** [comment]
Remove all references to magnific popup in functions.php, scripts.js, and the sass include.

functions.php
`// Magnific Popup (lightbox) - http://dimsemenov.com/plugins/magnific-popup/
	wp_enqueue_script( 'scaffolding-magnific-popup-js', get_stylesheet_directory_uri() . '/libs/js/jquery.magnific-popup.min.js', array( 'jquery' ), '1.0.0', true );`

js/scripts.js
`// Lightbox - http://dimsemenov.com/plugins/magnific-popup/
	if ($.fn.magnificPopup) {
		$image_selector = 'a[href$=".jpg"], a[href$=".jpeg"], a[href$=".png"], a[href$=".gif"]';

		// single image popup
		$($image_selector).each(function(){
			if ($(this).parents('.gallery').length == 0) {
				$(this).magnificPopup({type:'image'});
			}
		});

		// gallery popup
		$('.gallery').each(function() {
			$(this).magnificPopup({
				type: 'image',
				delegate: $image_selector,
				gallery: {
					enabled: true,
					preload: [1,2]
				},
				image: {
					titleSrc: function(item) {
						return item.el.parents('.gallery-item').find('.gallery-caption').text();
					}
				}
			});
		});
	}`

scss/style.scss
`@import "libs/magnific-popup"; // magnific lightbox styles - see https://github.com/dimsemenov/Magnific-Popup for more info`
