### ISSUE TITLE
Failed to Import compass

### ISSUE THREAD

**Issue by Tanmccuin** [hallme/scaffolding#123]
> File to import not found or unreadable: compass Parent style sheet: /scss/utilities/_mixins.scss on line 35:1 of /scss/utilities/_mixins.scss /scss/style.scss

Unsure of workflow getting started - but do I need to do something further as far as importing assets?

**Comment by Tanmccuin** [comment]
issue resolved by setting the style.scss to compile utilizing compass

**Comment by gthayer** [comment]
Glad to hear you git it working @Tanmccuin!
