### ISSUE TITLE
Adjusting sidebars

### ISSUE THREAD

**Issue by Tanmccuin** [hallme/scaffolding#124]
Is there any documentation on how best to approach sidebars within Scaffolding? 

It seems obtuse to me currently that sidebars are called in the footer, and controlled in the header, when it's the main body content they appear in? Almost all of the templates I've worked with over the years keep sidebar in the page.php level template. With the Scaffolding approach, so far as I can tell, custom page templates will require custom footer templates to control whether or not sidebars appear (at least, at a template level...) I'm assuming there's a reason? could you enlighten me?

**Comment by jlavoie13** [comment]
We generally use a plugin to control what pages widgets appear on like [Dynamic Widgets](https://wordpress.org/plugins/dynamic-widgets/) or [Jetpack's Visibility](https://jetpack.com/support/widget-visibility/) but by default the left and right sidebar are used for all templates. This is actually something I've addressed in the [Woo Integration branch](https://github.com/hallme/scaffolding/tree/woo-integration) and will move to master soon.
