### ISSUE TITLE
Missing default Bootstrap classes

### ISSUE THREAD

**Issue by novosadskigari** [hallme/scaffolding#127]
Hi guys,

I started using scaffolding theme as a base for all my themes recently and I noticed some default classes from Bootstrap are missing like container, hide-*

Any idea what I'm doing wrong?

**Comment by matt-h** [comment]
Hi @novosadskigari 

Scaffolding does not include Bootstrap in the theme, it has a barebones set of [styles](https://github.com/hallme/scaffolding/tree/master/scss) that you can expand on.

The only thing it does take from Bootstrap is the [Grid system](http://getbootstrap.com/css/#grid) which is included [here](https://github.com/hallme/scaffolding/blob/master/scss/elements/_bootstrap-grid.scss).

You can certainly add Bootstrap to the SCSS and/or JS if you do wish to use the full or part of that framework.

**Comment by novosadskigari** [comment]
Hey @matt-h 

thanks for the super fast reply and the clarification.

Is there some detailed documentation that I can find?

I'm facing another really annoying issue with mobile menu (I only see parent menu items and nothing else! They are in the code but not shown in the front end).

Thanks!

**Comment by jlavoie13** [comment]
The Bootstrap grid in Scaffolding is quite outdated. We will look into updating that; maybe that is your issue.

As far as the menu, I have not seen/heard anything like that. Are you using Scaffolding out of the box or have you made any significant modifications to the menu? Also what device are you using?

**Comment by novosadskigari** [comment]
I know it's ungrateful to ask, but any estimate on the grid update maybe? :)
