### ISSUE TITLE
Is this based on Bones or _S??

### ISSUE THREAD

**Issue by fregan** [hallme/scaffolding#129]
The website here says it is based on _S, http://scaffolding.io/

However the readme file, both here and there, states the theme is based on Bones. Which is it?

**Comment by matt-h** [comment]
Hi Lee, 

The first version of scaffolding was a fork of bones. Since then we have ported a lot of things FROM _S

**Comment by matt-h** [comment]
Sorry, hit submit early. 

Since then we have ported a lot of things from _S and removed a lot of the stuff from Bones that I don't think that much from Bones even remains anymore.

**Comment by fregan** [comment]
Oh Okay, great to know! I started out with Bones years ago and had my company just switch over to _S and came across your theme. Great resource and thank you for the hard work.
