### ISSUE TITLE
Failed to load content css

### ISSUE THREAD

**Issue by bryanf123** [hallme/scaffolding#130]
Since the upgrade to wordpress 4.8 I get this error when editing pages/posts Failed to load content css: https://mealsonwheelswny.org/wp-content/themes/mealsowheels/css/editor-styles.css

**Comment by gthayer** [comment]
Hi @bryanf123. Are you still experiencing this? The file appears to be loading for me.

Can you also double check whether WP_DEBUG is turned on in wp_config.php. It is usually best practice to disable this on live sites.

**Comment by gthayer** [comment]
Looks like this might also be a larger issue with the 4.8 release too:

https://wordpress.org/support/topic/wordpress-4-8-editor-failed-to-load-content-css/

If you are still experiencing this, try:
- Removing one of the imports. They appear redundant.
- Changing the urls from: `https://fonts.googleapis.com/` to `//fonts.googleapis.com/`

**Comment by bryanf123** [comment]
Thank you, removing one of the imports did the trick.

<http://manzellamarketing.com/>

*Bryan FreeDirector of Digital Design*

5360 Genesee St., Suite 203
Bowmansville, NY 14026
Phone: 716.681.6565, ext. 220 <716.681.6565%2C%20ext.%220>
Fax: 716.681.5678
bryanf@manzellamarketing.com
<https://www.facebook.com/ManzellaMarketing/>
<https://twitter.com/ManzellaMktg>
<https://www.linkedin.com/company/118012?trk=tyah&trkInfo=clickedVertical%3Acompan+y%2CclickedEntityId%3A118012%2Cidx%3A3-2-+13%2CtarId%3A1463146627769%2Ctas%3Amanze>
<https://www.instagram.com/manzellamarketing/>
<http://manzellamarketing.com/blog/>
