### ISSUE TITLE
Woocommerce Subcategories

### ISSUE THREAD

**Issue by bryanf123** [hallme/scaffolding#136]
When I upgrade to woocommerce 3.3.1 and later the site no longer recognizes subcategories within a category and instead shows products. When I revert to the 2017 theme the subcategories show up fine. Is there a fix for this?

**Comment by jlavoie13** [comment]
Hi, I'm unable to help debug without knowing what sort of customizations you've made to the theme. I cannot replicate this myself with the current version of scaffolding. If you can provide any other insight, I'd be happy to help.

**Comment by bryanf123** [comment]
Hello,

I have not made a lot of customizations to the theme, mostly deleted the
banner, and added some widget areas for the header and footer other than
that its the same as when I downloaded it. I will do my best to outline the
issue here....

On the current live site I have not updated to the newest version of
woocommerce and this is how it funtions...

first on the shop page you get two categories (see screenshot)


If you click on Vetrenarian then you are taken to the below screen and
presented with subcategories and from there you can select a subcategory
and view products within that categories. Thats how it was setup and thats
what I want.


BUT when I update to the newest woocommerce on a staging version of the
site the subcategories fail to appear and instead it shows some of the
products (see screenshot)




When I switched to the 2017 theme the subcategories showed back up.

Any help would be appreciated, Thank you for taking the time,


<http://manzellamarketing.com/>

*Bryan FreeDirector of Digital Design*

5360 Genesee St., Suite 203
Bowmansville, NY 14026
Phone: 716.681.6565, ext. 220 <716.681.6565%2C%20ext.%220>
Fax: 716.681.5678
bryanf@manzellamarketing.com
<https://www.facebook.com/ManzellaMarketing/>
<https://twitter.com/ManzellaMktg>
<https://www.linkedin.com/company/118012?trk=tyah&trkInfo=clickedVertical%3Acompan+y%2CclickedEntityId%3A118012%2Cidx%3A3-2-+13%2CtarId%3A1463146627769%2Ctas%3Amanze>
<https://www.instagram.com/manzellamarketing/>
<http://manzellamarketing.com/blog/>

**Comment by jlavoie13** [comment]
The screenshots didn't come through

**Comment by bryanf123** [comment]
I have attached the screenshots here but if that doesnt work you can click
through on the sites.

Live site with subcategories working: https://ambickford.com/

Staging sites with the most up to date version of woocommerce and borken
subcategories: http://staging.ambickford.flywheelsites.com/
( Privacy login info Username: flywheel Password: sulky-potato)

<http://manzellamarketing.com/>

*Bryan FreeDirector of Digital Design*

5360 Genesee St., Suite 203
Bowmansville, NY 14026
Phone: 716.681.6565, ext. 220 <716.681.6565%2C%20ext.%220>
Fax: 716.681.5678
bryanf@manzellamarketing.com
<https://www.facebook.com/ManzellaMarketing/>
<https://twitter.com/ManzellaMktg>
<https://www.linkedin.com/company/118012?trk=tyah&trkInfo=clickedVertical%3Acompan+y%2CclickedEntityId%3A118012%2Cidx%3A3-2-+13%2CtarId%3A1463146627769%2Ctas%3Amanze>
<https://www.instagram.com/manzellamarketing/>
<http://manzellamarketing.com/blog/>

**Comment by bryanf123** [comment]
Any News on this?

**Comment by jlavoie13** [comment]
The markup on the live site vs. the staging site is completely different. I'm sorry, I can't help you further on this.
