### ISSUE TITLE
Refresh loads at top of page

### ISSUE THREAD

**Issue by bryanf123** [hallme/scaffolding#138]
Hello,

When the page reloads it loads at the top of the page and I was wondering how to disable this feature.

**Comment by jewels-illustrates** [comment]
I'm having this same issue, I want the page to reload at the same spot but it forces the user to the top of the page on my site here: http://crfs.flywheelsites.com

I noticed that a site I previously built using an older version of this theme doesn't force you to the top when you reload if the link helps you at all: http://vecwny.com/

**Comment by jlavoie13** [comment]
Are you talking about linking to an ID on the page like this http://vecwny.com/our-services/#inner-footer or something else?

**Comment by bryanf123** [comment]
Yes, its fine if you are on that page but if you want to link to a spot on
a page from another it will load the site at the top. In general the newer
theme seems to always load the site at the top of the page every time. I
was just wondering if we could deactivate this.

<http://manzellamarketing.com/>

*Bryan FreeDirector of Digital Design*

5360 Genesee St., Suite 203
Bowmansville, NY 14026
Phone: 716.681.6565, ext. 220 <716.681.6565%2C%20ext.%220>
Fax: 716.681.5678
bryanf@manzellamarketing.com
<https://www.facebook.com/ManzellaMarketing/>
<https://twitter.com/ManzellaMktg>
<https://www.linkedin.com/company/118012?trk=tyah&trkInfo=clickedVertical%3Acompan+y%2CclickedEntityId%3A118012%2Cidx%3A3-2-+13%2CtarId%3A1463146627769%2Ctas%3Amanze>
<https://www.instagram.com/manzellamarketing/>
<http://manzellamarketing.com/blog/>

**Comment by jewels-illustrates** [comment]
Yes like that.

**Comment by jlavoie13** [comment]
@jewels-illustrates - This seems to be related to Modernizr. I tested the version you are using and was able to replicate it. If you are not using it to test anything I would recommend removing if from the theme.

@bryanf123 - I tested the version of Modernizr you are using but could not replicate your issue.

**Comment by jewels-illustrates** [comment]
@jlavoie13  thank you!
