### ISSUE TITLE
Replace Compass with Node SASS

### ISSUE THREAD

**Issue by TimBHowe** [hallme/scaffolding#147]
[Compass](http://compass-style.org/) is no longer in active development.

Based on the active development and the use in the [Underscores](https://github.com/Automattic/_s/) theme we will replace compass with Node SASS

- Remove the [config.rb](https://github.com/hallme/scaffolding/blob/master/scss/config.rb)
- Remove the [compass gulp task](https://github.com/hallme/scaffolding/blob/master/gulpfile.js#L53)
-  Set up the npm scripts from underscores https://github.com/Automattic/_s/blob/master/package.json
- Update documentation

**Comment by matt-h** [comment]
I'd suggest not using gulp and use the npm scripts from underscores https://github.com/Automattic/_s/blob/master/package.json

**Comment by vielmetti** [comment]
https://sass-lang.com/blog/libsass-is-deprecated

"After much discussion among the Sass core team, we’ve come to the conclusion that it’s time to officially declare that LibSass and the packages built on top of it, including Node Sass, are deprecated."

The suggested replacement is "Dart Sass" https://sass-lang.com/dart-sass

**Comment by jlavoie13** [comment]
#157 replaced compass with laravel-mix
