### ISSUE TITLE
small columns mixup

### ISSUE THREAD

**Issue by merijnorama** [hallme/scaffolding#92]
When setting up the starter theme out of the box / default (and when using the left sidebar), I noticed the columns getting mixed up in the sm-template (see attached screenshot, left sidebar appears on right, content on left).
I tried resolving this in bootstrap-grid.scss since I suspect is has something to do with the  push-pull of the sm-columns but so far I have not succeeded.

Seen in Google Chrome V 39.0.2171.95 / Windows 7

![scaffoldingio_sm_columns](https://cloud.githubusercontent.com/assets/1884613/5705040/9f2655ac-9a76-11e4-8260-d72d37489516.jpg)

**Comment by jlavoie13** [comment]
This issue should have been resolved in the latest update. If you continue to experience problems I'll be happy to take another look.

**Comment by rclations** [comment]
for reference - b8e7d3f4c0a6d3ba699de7e40d49277a337d41e3

thanks for the report, @merijnorama !
I'm going to close this ticket for now, but feel free to reopen if you're still seeing the issue with the current version.

**Comment by merijnorama** [comment]
Thank you for your quick response @rclations and @jlavoie13 
I will get the latest version from github and try again.
