### ISSUE TITLE
Scaffolding importing fonts multiple times

### ISSUE THREAD

**Issue by gthayer** [hallme/scaffolding#93]
If you look in style.css, you'll see that google fonts are being imported multiple times. Not sure why, yet.

Example: http://woocommerce.halltestspace.wpengine.com/wp-content/themes/scaffolding-woocommerce/css/style.css

**Comment by jlavoie13** [comment]
I think we should enqueue the style and remove the @import from sass.

**Comment by rclations** [comment]
i'm into it. let's make it happen

**Comment by jlavoie13** [comment]
I'm on it.
