### ISSUE TITLE
Possible Gravity Forms conflict

### ISSUE THREAD

**Issue by jo-greenwood** [hallme/scaffolding#95]
I have 3 issues when using gravity forms with Scaffolding (issues don't occur with default wordpress theme):

1. I have a select field in my form but when I click on it the dropdown is hidden behind the element below. Class 'chosen-drop' has a z-index of 1010. Increasing this does nothing.

2. If the form is submitted with errors, the returned page (which highlights the errors) includes a form with a non-ajax select dropdown. In this case the dropdown isn't hidden but it doesn't fit in aesthetically with the rest of the form.

3. If the form is submitted with errors, the returned page doesn't show checkboxes. They can be found in the page source but they no longer have a class of 'icheckbox_square' and no width is set for them so they are not visible.

I'm afraid my site is not currently publicly accessible but I can provide screenshots and/or code if necessary.

**Comment by TimBHowe** [comment]
#99

**Comment by jlavoie13** [comment]
This is in reference to chosen and icheck which is no longer on the theme.
