### ISSUE TITLE
Theme Checker Errors

### ISSUE THREAD

**Issue by TimBHowe** [hallme/scaffolding#98]
* REQUIRED:.bypostauthor css class is needed in your theme css.
* RECOMMENDED: Text domain problems in includes/custom-post-type.php. You have not included a text domain!
Line 186: 5 	=> isset( $_GET['revision'] ) ? sprintf( __( '%s restored to revision from %s' ), * * * * CUSTOM_POST_SINGULAR,  wp_post_rev
Line 190: 9 	=> sprintf( __( '%3$s scheduled for: <strong>%1$s</strong>. <a target='_blank' href='%2$s'>Preview %3$s</a>' ), date_i18n( __( 'M j, Y @ G:i' ), strtotime( $post->post_date ) ), esc_url( get_permali
* WARNING: The theme uses the add_shortcode() function. Custom post-content shortcodes are plugin-territory functionality.
* REQUIRED: The theme uses the register_post_type() function, which is plugin-territory functionality.
* REQUIRED: Please remove any extraneous directories like .git or .svn from the ZIP file before uploading it.
* RECOMMENDED: could not find the file readme.txt in the theme. Please see Theme_Documentation for more information.
* RECOMMENDED: No reference to add_theme_support( "title-tag" ) was found in the theme. It is recommended that the theme implement this functionality for WordPress 4.1 and above.
* RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
* INFO: Possible hard-coded links were found in the file includes/theme-guide.php.
Line 26: <li><a href='http://scaffolding.io' target='_blank'>Scaffolding Theme</a></li>
Line 29: <li><a href='http://docs.woothemes.com/documentation/plugins/woocommerce/' target='_blan
* INFO: Possible hard-coded links were found in the file includes/theme-guide.php.
Line 26: <li><a href='http://scaffolding.io' target='_blank'>Scaffolding Theme</a></li>
* INFO: includes/base-functions.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 679: require_once ( SCAFFOLDING_INCLUDE_PATH.'class-tgm-plugin-activation.php' )

**Comment by jlavoie13** [comment]
Let's kill the custom post type template.

**Comment by TimBHowe** [comment]
removed the custom-post-type.php include

https://github.com/hallme/scaffolding/commit/c0d468d887c1fef36cf7e5f6e8b395636aff9c80
