### ISSUE TITLE
Update Gravity Forms Styles

### ISSUE THREAD

**Issue by jlavoie13** [hallme/scaffolding#99]
Make sure the styles are compatible with latest version. Do we care about backwards compatibility?

**Comment by TimBHowe** [comment]
Does it support ie8? We should try and have it support all the browsers we support, so if we can get it to work with IE8 we should.

**Comment by jlavoie13** [comment]
I meant specifically backwards compatibility with older versions of gravity forms but that's probably overkill.

**Comment by TimBHowe** [comment]
if we can help it. It should just be rather then updating the change class names we just add them to the styles. I don't think we need to kill our selves over it.

**Comment by TimBHowe** [comment]
Also should we take this out of scaffolding and make this a module user can add? As this is a payed plugin not everyone will have it. Thoughts?

**Comment by jlavoie13** [comment]
This is my thought...

![scaffoldingio](https://cloud.githubusercontent.com/assets/4210773/9284267/6adcdf52-42a8-11e5-9154-4838706950c2.png)

**Comment by TimBHowe** [comment]
Sweet! is that built or something we need to add?

**Comment by jlavoie13** [comment]
Yes, I've built this out.
